<a href="https://colab.research.google.com/github/kishoremkv/gen-ai-fundamentals/blob/main/day1/PyTorch_1_Exercise_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import the __`torch`__ package

In [ ]:
import torch as pt
pt.manual_seed(0);

## Create a vector of ten zeros

In [ ]:
pt.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [ ]:
x = pt.zeros(10)
x[4] = 1
x

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [ ]:
x = pt.arange(10, 50)
x

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

## Reverse the previous vector

In [ ]:
x.flip(0)

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
pt.arange(9).reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [ ]:
v = pt.tensor([1, 2, 0, 0, 4, 0]) # Given
v

tensor([1, 2, 0, 0, 4, 0])

In [ ]:
indices = v.nonzero()
indices

tensor([[0],
        [1],
        [4]])

## Create a 5x5 identity matrix

In [ ]:
pt.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Create a 3x3x3 array with random values

In [ ]:
rand33 = pt.randn(3, 3, 3)
rand33

tensor([[[ 1.0395,  0.3582, -0.0033],
         [-0.5344,  1.1687,  0.3945],
         [ 1.9415,  0.7915,  0.0335]],

        [[ 0.7101, -1.5353, -2.4351],
         [-0.0729, -0.0340,  0.9625],
         [ 0.3492, -0.9215, -0.0562]],

        [[-0.7015, -0.4637,  1.9218],
         [-0.4025,  0.1239,  1.1648],
         [ 0.9234,  1.3873,  1.3750]]])

## Find the minimum and maximum values generated in the previous step

In [ ]:
rand33.min(), rand33.max()

(tensor(-2.4351), tensor(1.9415))

## Create a vector with 30 random values and find its mean

In [ ]:
rand30 = pt.randn(30)
rand30.mean()

tensor(-0.0257)

## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [ ]:
rand55 = pt.zeros(5, 5)
rand55[0, :] = 1
rand55[:, 0] = 1
rand55[-1, :] = 1
rand55[:, -1] = 1
rand55

tensor([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]])

## Try to predict the output of each of the following cells before running them

In [ ]:
0 * float('nan')

nan

In [ ]:
float('nan') == float('nan')

False

In [ ]:
float('inf')

inf

In [ ]:
float('nan') - float('nan')

nan

In [ ]:
0.3 == 3 * 0.1

False

In [ ]:
pt.tensor([0]) // pt.tensor([0]) #crashes the kernel :) continue with the next cell

RuntimeError: ZeroDivisionError

In [ ]:
import torch as pt #this is in case you crashed on the previous cell
pt.tensor([0]) // pt.tensor([0.0])

tensor([nan])

In [ ]:
nan_scalar = pt.tensor([float('nan')])

pt.isnan(nan_scalar)

tensor([True])

In [ ]:
pt.tensor([0]) / pt.tensor([0.0])

tensor([nan])

## Find the integer part of the following array using four different methods:

In [ ]:
a = pt.randn((10,), dtype = pt.float32)
a

tensor([ 0.3066, -0.8420, -0.1174,  0.3627, -0.3253, -0.5434,  0.4304,  0.2640,
         0.7012, -0.8035])

In [ ]:

a.floor()



tensor([ 0., -1., -1.,  0., -1., -1.,  0.,  0.,  0., -1.])

In [ ]:
a.trunc()


tensor([0., -0., -0., 0., -0., -0., 0., 0., 0., -0.])

In [ ]:
pt.floor(a)


tensor([ 0., -1., -1.,  0., -1., -1.,  0.,  0.,  0., -1.])

In [ ]:
pt.trunc(a)

tensor([0., -0., -0., 0., -0., -0., 0., 0., 0., -0.])

## Create a vector of 10 values from 0 to 1, both included

In [ ]:
pt.linspace(0, 1, 10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:


pt.linspace(0, 1, 12)[1:-1]


tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

## Subtract the mean of each row of the following matrix

In [ ]:
m = pt.rand(3, 3)
m

tensor([[0.1753, 0.4431, 0.6432],
        [0.5159, 0.1636, 0.0958],
        [0.8985, 0.5814, 0.9148]])

In [ ]:
mean = m.mean(dim=1, keepdim=True)
m - mean

tensor([[-0.2453,  0.0226,  0.2227],
        [ 0.2575, -0.0949, -0.1626],
        [ 0.1003, -0.2168,  0.1166]])

## Add 1,000,000 numbers together using __`torch`__ vectorized operations

In [ ]:

a = pt.arange(1000000)
a.sum()


tensor(499999500000)

## Create a 4x4 array of the first 16 powers of 3

In [ ]:
pt.pow(3, pt.arange(16)).reshape(4, 4)

tensor([[       1,        3,        9,       27],
        [      81,      243,      729,     2187],
        [    6561,    19683,    59049,   177147],
        [  531441,  1594323,  4782969, 14348907]])